#!/bin/bash --login
#SBATCH -J ADCIRC_COLDSTART_SPINUP
#SBATCH -A coastal
#SBATCH --mail-type=ALL
#SBATCH --mail-user=example@email.gov
#SBATCH --error=ADCIRC_COLDSTART_SPINUP.err.log
#SBATCH --output=ADCIRC_COLDSTART_SPINUP.out.log
#SBATCH -n 1020
#SBATCH -N 15
#SBATCH --time=06:00:00
#SBATCH --partition=development

set -e

source ..\..\..\..\input\modulefiles\envmodules_intel.stampede
ibrun ../../../../input/bin/NEMS.x
