#!/bin/bash --login
#SBATCH -J ADCIRC_SETUP_unperturbed
#SBATCH -A coastal
#SBATCH --mail-type=ALL
#SBATCH --mail-user=example@email.gov
#SBATCH --error=ADCIRC_SETUP_unperturbed.err.log
#SBATCH --output=ADCIRC_SETUP_unperturbed.out.log
#SBATCH -n 1
#SBATCH -N 1
#SBATCH --time=06:00:00
#SBATCH --partition=development

set -e

source ..\..\..\..\..\input\modulefiles\envmodules_intel.stampede
ibrun ../../../../../input/bin/adcprep --np 1020 --partmesh
ibrun ../../../../../input/bin/adcprep --np 1020 --prepall
