#!/bin/bash --login
#SBATCH -J ADCIRC_COLDSTART_unperturbed
#SBATCH -A coastal
#SBATCH --mail-type=ALL
#SBATCH --mail-user=example@email.gov
#SBATCH --error=ADCIRC_COLDSTART_unperturbed.err.log
#SBATCH --output=ADCIRC_COLDSTART_unperturbed.out.log
#SBATCH -n 602
#SBATCH -N 16
#SBATCH --time=06:00:00

set -e

source ../../../../../input/modulefiles/envmodules_intel.hera
srun ../../../../../input/bin/NEMS.x
