#!/bin/bash
#SBATCH -J ADCIRC_SETUP_SPINUP
#SBATCH -A coastal
#SBATCH --mail-type=ALL
#SBATCH --mail-user=example@email.gov
#SBATCH --error=ADCIRC_SETUP_SPINUP.err.log
#SBATCH --output=ADCIRC_SETUP_SPINUP.out.log
#SBATCH -n 1
#SBATCH -N 1
#SBATCH --time=06:00:00

set -e

source ../../../input/modulefiles/envmodules_intel.hera
srun ../../../input/bin/adcprep --np 600 --partmesh
srun ../../../input/bin/adcprep --np 600 --prepall
