#!/bin/bash --login
#SBATCH -J ADC_MESH_DECOMP
#SBATCH -A coastal
#SBATCH --mail-type=ALL
#SBATCH --mail-user=example@email.gov
#SBATCH --error=ADC_MESH_DECOMP.err.log
#SBATCH --output=ADC_MESH_DECOMP.out.log
#SBATCH -n 1
#SBATCH -N 1
#SBATCH --time=00:30:00
#SBATCH --partition=development

set -e

source /work/07531/zrb/stampede2/builds/ADC-WW3-NWM-NEMS/modulefiles/envmodules_intel.stampede
ibrun adcprep --np 1020 --partmesh
ibrun adcprep --np 1020 --prepall
