#!/bin/bash --login
#SBATCH -J ADCIRC_MESH_PARTITION
#SBATCH -A coastal
#SBATCH --mail-type=ALL
#SBATCH --mail-user=example@email.gov
#SBATCH --error=ADCIRC_MESH_PARTITION.err.log
#SBATCH --output=ADCIRC_MESH_PARTITION.out.log
#SBATCH -n 1
#SBATCH -N 1
#SBATCH --time=00:30:00
#SBATCH --partition=development

set -e

source /work/07531/zrb/stampede2/builds/ADC-WW3-NWM-NEMS/modulefiles/envmodules_intel.stampede

ibrun adcprep --np 11 --partmesh
ibrun adcprep --np 11 --prepall
