#!/bin/bash --login
#SBATCH -J ADCIRC_HOTSTART_unperturbed
#SBATCH -A coastal
#SBATCH --mail-type=ALL
#SBATCH --mail-user=example@email.gov
#SBATCH --error=ADCIRC_HOTSTART_unperturbed.err.log
#SBATCH --output=ADCIRC_HOTSTART_unperturbed.out.log
#SBATCH -n 600
#SBATCH -N 15
#SBATCH --time=06:00:00

set -e

source ../../../../../input/modulefiles/envmodules_intel.hera
srun ../../../../../input/bin/padcirc
