#!/bin/bash --login
#SBATCH -J ADC_MESH_DECOMP
#SBATCH -A coastal
#SBATCH --mail-type=ALL
#SBATCH --mail-user=example@email.gov
#SBATCH --error=ADC_MESH_DECOMP.err.log
#SBATCH --output=ADC_MESH_DECOMP.out.log
#SBATCH -n 1
#SBATCH -N 1
#SBATCH --time=00:30:00

set -e

source /scratch2/COASTAL/coastal/save/shared/repositories/ADC-WW3-NWM-NEMS/modulefiles/envmodules_intel.hera
srun adcprep --np 600 --partmesh
srun adcprep --np 600 --prepall
