#!/bin/bash --login
#SBATCH -J ADCIRC_MESH_PARTITION
#SBATCH -A coastal
#SBATCH --mail-type=ALL
#SBATCH --mail-user=example@email.gov
#SBATCH --error=ADCIRC_MESH_PARTITION.err.log
#SBATCH --output=ADCIRC_MESH_PARTITION.out.log
#SBATCH -n 1
#SBATCH -N 1
#SBATCH --time=00:30:00
#SBATCH --partition=coastal

set -e

source /scratch2/COASTAL/coastal/save/shared/repositories/ADC-WW3-NWM-NEMS/modulefiles/envmodules_intel.hera
DIRECTORY="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

pushd ${DIRECTORY} >/dev/null 2>&1
srun adcprep --np 11 --partmesh
srun adcprep --np 11 --prepall
popd >/dev/null 2>&1
